server:
  port: 9080
zuul:
  routes:
    doctor:
      url: http://localhost:9081
      sensitive-headers:
    booking:
      url: http://localhost:9083
      sensitive-headers:
    payment:
      url: http://localhost:9084
      sensitive-headers:
    patient:
      url: http://localhost:9082
      sensitive-headers:
    main:
      url: http://localhost:9080
      sensitive-headers:
